### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sorenwacker** [mpcrlab/MolecularTransformerEmbeddings#1]
Hi, 

this is an amazing contribution and very helpful work for many in the field. 
I wonder if there is any license attached and what are the conditions for re-using the code. 

Cheers

**Comment by ptmorris03** [comment]
I updated the repository with the MIT License and added citation details in the Readme file.

In general, this is research code provided "as-is" for reuse, exploration, or replication and is not optimized for performance. Contributions/improvements are welcome, and feel free to reach out if there are any issues/questions.

Best Wishes!
