### ISSUE TITLE
Suggestion: conda environment or docker

### ISSUE THREAD

**Issue by sorenwacker** [mpcrlab/MolecularTransformerEmbeddings#3]
Hi, I tried to install the dependencies, but it seems to install it with

    pip install -r environement.txt

does not capture all the dependencies. It was also not 100% clear which python version was used. Python 3 could be anything from 3.0.0 until 3.10, I believe is the latest.

I wonder if it would be feasible for you to provide a conda environment file for the matter?

I was not able to install the requirements on my current system without running into errors, though I was able to run the transformer in my general purpose torch environment.

**Comment by sorenwacker** [comment]
This is a really great contribution!

**Comment by ptmorris03** [comment]
I finally added a Dockerfile and put a prebuilt image on dockerhub. It's specific to Cuda 10.0 (driver version 410 or later). If you want a different Cuda version you can switch the first line of the Dockerfile, update the corresponding torch version in requirements.txt, and rebuild.

**Comment by sorenwacker** [comment]
Amazing :-)

________________________________
